#!/bin/sh
host_ip=`ifconfig -a|grep -o -e 'inet [0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}'|grep -v "127.0.0"|awk '{print $2}'`
nohup java -jar \
-Dcom.sun.management.jmxremote=true \
-Djava.rmi.server.hostname=$host_ip \
-Dcom.sun.management.jmxremote.port=$2  \
-Dcom.sun.management.jmxremote.ssl=false \
-Dcom.sun.management.jmxremote.authenticate=false \
$1 >/dev/null 2>&1 &

